version: 0.2

phases:
  install:
    commands:
      - yum -y install moreutils #wine
      - ProjectHash=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - npm install -g webpack webpack-cli #electron-builder
      - npm install
  build:
    commands:
      - webpack --mode=production
      #- electron-builder -w
      - aws cloudformation package --template-file ./template.yml --s3-bucket ${Bucket} --output-template-file serverless.yml
  post_build:
    commands:
      - jq '.Parameters.ProjectName = "'$ProjectName'"' config.json | sponge config.json
      - jq '.Parameters.ProjectHash = "'$ProjectHash'"' config.json | sponge config.json
      - jq '.Parameters.Environment = "'$Environment'"' config.json | sponge config.json
      - jq '.Parameters.DeploymentBucket = "'$DeploymentBucket'"' config.json | sponge config.json
artifacts:
  secondary-artifacts:
    S3SiteFiles:
      discard-paths: yes
      files:
        - dist/*
    BuildOutput:
      discard-paths: yes
      files:
        - serverless.yml
        - config.json
