version: 0.2

phases:
    install:
        commands:
            - npm install -g webpack webpack-cli
            - npm install
    build:
        commands:
            - webpack --mode=production
            #- zip -r dist.zip dist/dist/

artifacts:
    files:
        dist/*
    discard-paths: yes