version: 0.2

phases:
    install:
        commands:
            - npm install -g webpack
            - npm install
    build:
        commands:
            - webpack --mode=production
            - zip -r dist.zip dist/

artifacts:
    files:
        dist.zip
    discard-paths: yes