AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    
  ProjectHash:
    Type: String

  Environment:
    Type: String
    Default: dev
    
Mappings:
  URLs:
    prod:
      domain: dev.mckayhear.es
      zoneId: Z2BASL1172N9HA
    dev:
      domain: dev.mckayhear.es
      zoneId: Z2BASL1172N9HA
    
Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap ["URLs", !Ref Environment, domain]
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  StaticSitePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource:
              - !Sub ${StaticSiteBucket.Arn}/*
      Bucket: !Ref StaticSiteBucket

  StaticSiteRecordSets:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: Forward to Environment
      HostedZoneId: !FindInMap ["URLs", !Ref Environment, zoneId]
      RecordSets:
        - Name: !Sub
            - ${bucket}.
            - bucket: !FindInMap ["URLs", !Ref Environment, domain]
          Type: A
          AliasTarget:
            DNSName: !GetAtt StaticSiteBucket.WebsiteURL
            HostedZoneId: !FindInMap ["URLs", !Ref Environment, zoneId]
    # Static site
    # Game Code
    # Lambda API
