AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    
  ProjectHash:
    Type: String
    
  Environment:
    Type: String
    Default: dev
    
Mappings:
  URLs:
#    prod:
#      root: mckayhear.es
#      domain: dev.mckayhear.es
#      zoneId: Z2BASL1172N9HA
#      s3endpoint: s3-website-ap-southeast-2.amazonaws.com
#      s3zoneId: Z1WCIGYICN2BYD
    dev:
      domain: dev.mckayhear.es
      root: mckayhear.es
      zoneId: Z2BASL1172N9HA
      s3endpoint: s3-website-ap-southeast-2.amazonaws.com
      s3zoneId: Z1WCIGYICN2BYD

Resources:
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap ["URLs", !Ref Environment, domain]
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  StaticSitePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource:
              - !Sub ${StaticSiteBucket.Arn}/*
      Bucket: !Ref StaticSiteBucket

  StaticSiteRecordSets:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: Forward to Environment
      HostedZoneName: !Sub
        - ${bucket}.
        - bucket: !FindInMap ["URLs", !Ref Environment, root]
      RecordSets:
        - Name: !Sub
            - ${bucket}.
            - bucket: !FindInMap ["URLs", !Ref Environment, domain]
          Type: A
          AliasTarget:
            HostedZoneId: !FindInMap ["URLs", !Ref Environment, s3zoneId]
            DNSName: !FindInMap ["URLs", !Ref Environment, s3endpoint]
    # Static site
    # Game Code
    # Lambda API
    
  #Forward this from something like devapi.mckayhear.es
  LambdaApi:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: handler
      InlineCode: |
        def handler(_, __):
          print("Hello, world")
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /path
            Method: get
